### ISSUE TITLE
can't get my cheer up seeds to show on main page

### ISSUE THREAD

**Issue by BrianLoveGa** [BrianLoveGa/project-2-cheerupApp#1]
was trying to use the methods from the gaffey (giffy ... gif posting) lab to have a js file attached to index file to render the cheer ups. I like the grid layout and thought having them like this would be smooth for adding and deleting them... but since it's a file from my computer not a link from a website they just aren't appearing...

**Comment by BrianLoveGa** [comment]
Header , nav bar, and footer show up - so something is working ... in console log of local host in browser it says "cheerUps:37 GET http://localhost:3000/frontend/site.js net::ERR_ABORTED 404 (Not Found)" & "Unchecked runtime.lastError: The message port closed before a response was received."    earlier terminal with nodemon running was saying "error document not defined on frontend site.js" - but now I'm not even getting that...

**Comment by aspittel** [comment]
Your home page isn't rendering anything! https://github.com/BrianLoveGa/project-2-cheerupApp/blob/master/views/index.hbs and your site.

The process for hosting static javascript files is the same as the process for hosting css files
- create public folder
- host as static assets
- put JS file in public folder
- link script in your HTML file

**Comment by BrianLoveGa** [comment]
![Screen Shot 2019-10-04 at 5 16 10 PM](https://user-images.githubusercontent.com/53150373/66240470-b8d10880-e6ca-11e9-9d05-b3643b51e8ef.png)


moved js file - but still same errors in console log and no cheer ups showing up . no errors in any terminal windows

in earlier projects used layout as main page - index file was for home page in layout & other views rendered through layout file also (edit, add, show by id, ect...)

**Comment by BrianLoveGa** [comment]
<img width="1089" alt="Screen Shot 2019-10-04 at 5 26 10 PM" src="https://user-images.githubusercontent.com/53150373/66241028-174ab680-e6cc-11e9-950f-a1f1dd322907.png">



tried it with <script src="../public/JavaScript/site.js"></script>  just above </body > up top in head with css link, and here as pictured - same errors everytime....

**Comment by BrianLoveGa** [comment]
remove ../public/ from <script src="../public/JavaScript/site.js"></script>

change to <script src="/JavaScript/site.js"></script> - console log message coming thru!

**Comment by BrianLoveGa** [comment]
One prob down ... more to come I'm sure. 

__Thanks Prof Ali!__
