### ISSUE TITLE
Stuck getting create routes to POST for new user or new Cheerup

### ISSUE THREAD

**Issue by BrianLoveGa** [BrianLoveGa/project-2-cheerupApp#2]
__Description__ 
Can't get create new user or create new cheer to work (post) .
******
__Code__

in cheer.js controller

/// to make a new one exist  ---  !!  not working
// router.put("/", (req, res) => {
//   CheerUps.create(req.body).then(cheers => {
//     res.redirect("/cheerUps");
//   });
// });
// router.put("/newCheer", (req,res)=>{
//   CheerUps.create(req.body)
//   console.log(req.body)
//   .then(cheer =>{
//     console.log(cheer)
//     res.redirect("/cheerUps");
//   })
//   .catch(err => console.error(err)
// );
// });
router.post("/", (req, res) => {
  CheerUps.create(req.body).then(cheers => {
    res.redirect("/");
  });
});
router.post("/newCheer", (req,res)=>{
  CheerUps.create(req.body)
  console.log(req.body)
  .then(cheer =>{
    console.log(cheer)
    res.redirect("/cheerUps");
  })
  .catch(err => console.error(err)
);
});
///   end of prob area
*****
code at newCheer.hbs view - minus opening < tags

h3>Add a ' Cheer Up ' to our list  /h3>
div class="newCheerForm">
form  name="formNC" action="/" method="POST">
    section class="firstNC">
    label for="title">   Cheer Up Title       /label>

*****
__the error__

__terminal__ from nodemon index.js returns  
Error [ERR_HTTP_HEADERS_SENT]: /Users/blove/Desktop/GA - SEI/projects/secondProj/project-2-cheerupApp/views/layout.hbs: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:470:11)
    at ServerResponse.header (/Users/blove/Desktop/GA - SEI/projects/secondProj/project-2-cheerupApp/node_modules/express/lib/response.js:771:10)
    at ServerResponse.send (/Users/blove/Desktop/GA - SEI/projects/secondProj/project-2-cheerupApp/node_modules/express/lib/response.js:170:12)

which I'm not sure is anything to do with the problem - have tried moving the 
.catch(err => console.error(err)
line around to different spots but just the weird header from layout.hbs error in terminal
that error sometimes jumps up when just clicking around the page and updating cheers or users or deleting them.

__browser__ chrome returns
Error in tab title &
Cannot POST / - in top corner of blank white page

nothing in console log except runtime error - which i get often 
- faviocon error " "default-src 'none'" which is not my biggest worry 
- and Failed to load resource: the server responded with a status of 404 (Not Found) - whioch yeah there's no page

*****
__Why I think this error is happening__

my routes are wrong on controller file (router.put) or the top line of the form isn't connecting correctly at the ()* <form  name="formNC" action=("/")* method="POST">
******
__what I've tried__

puts and posts on controller js file- commenting all out and trying one at a time and all at a time

changing the form action='/' to action ='/cherrups' to ='/cheerUps/newUser' to ='/newUser' 

changed the res.redirect to read different things based on what was working in deletes and edits routes - that had no effect (or affect)

read pages and pages here
https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/routes

and read pages here 
https://expressjs.com/en/guide/routing.html

even tried the chain method ( . app.route()  ) towards bottom - but that didn't work either

If I can just get the new cheer or new user working it should be easy enough to fix the other... read update and delete all working fine thru localhost on seed files....

**Comment by aspittel** [comment]
You would post to `/cheerups` because all your routes are prefixed with `cheerups` in your index.js!

**Comment by BrianLoveGa** [comment]
so I commented out aaal put and post (except the one working for update by id from edit page) changed cheer.js code to 

router.post("/cheerUps", (req, res) => {
  CheerUps.create(req.body).then(cheers => {
    res.redirect("/cheerUps");
  });
});

and newCheer.hbs code to 

<form  name="formNC" action="/cheerUps" method="POST">
    <section class="firstNC">


and still get Cannot POST / cheerups  in browser and http error headers sent in console log with nodemon....

when I change newCheer.hbs to just  <form  name="formNC" action="/" method="POST">
    <section class="firstNC">

browser still says "cannot post / "

when I change newCheer.hbs to <form  name="formNC" action="/cheerUps/newCheer" method="POST">
    <section class="firstNC">

I still get browser error - "Cannot POST /cheerUps/newCheer"

when I change cheer controller to 
router.post("/cheerUps/", (req, res) => {
  CheerUps.create(req.body).then(cheers => {
    res.redirect("/cheerUps");
  });
});

or  router.post("/cheerUps/newCheer", (req, res) => {

still get cannot post ..... with form on new cheer up as 

<div class="newCheerForm">
<form  name="formNC" action="/cheerUps/newCheer" method="POST">
    <section class="firstNC">
or
<div class="newCheerForm">
<form  name="formNC" action="/cheerUps/" method="POST">
    <section class="firstNC">
or
<div class="newCheerForm">
<form  name="formNC" action="/" method="POST">
    <section class="firstNC">

still cannot post....

**Comment by aspittel** [comment]
Your post route shouldn't change -- it should be `/`, what you need to change is your form's `to`

**Comment by BrianLoveGa** [comment]
newCheer.hbs  form action set at 
```  
 <form  name="formNC" action="/" method="POST">
    
```
*****
cheer.js at

``` 
 router.post("/cheerUps", (req, res) => {
  CheerUps.create(req.body).then(cheers => {
    res.redirect("/cheerUps");
  });
});
`````
*****
click add new cheer button at bottom of form 
`````     
 <input class="buttonNCS" type="submit" value="Add New Cheer">
````` 

browser goes to "http://localhost:3000/"
and renders 
Cannot POST /

**Comment by BrianLoveGa** [comment]
added in error catch 
```
router.post("/cheerUps", (req, res) => {
  
  CheerUps.create(req.body).then(cheers => {
    
    res.redirect("/cheerUps");
    
  })
  .catch(err => console.error(err)
)
});
```

still nothing in nodemon console log or terminal console to point at why cannot post/ 
just the 
```
Error [ERR_HTTP_HEADERS_SENT]: /Users/blove/Desktop/GA - SEI/projects/secondProj/project-2-cheerupApp/views/layout.hbs: Cannot set headers after they are sent to the client
```

**Comment by aspittel** [comment]
This is the reverse! It should be `router.post("/"` and your form action should be `/cheerups`

**Comment by BrianLoveGa** [comment]
__Whoo HOO__
*****
__Prof ALI = the BEST__
```
router.post("/", (req, res) => {
  
  CheerUps.create(req.body).then(cheers => {
    console.log(req.body);
    console.log(cheers);
    res.redirect("/cheerUps");
    
  })
  .catch(err => console.error(err)
)
});
```

plus
```
<form  name="formNC" action="/cheerUps" method="POST">
```

__equals__

Finally Working !!!!!!

I knew it was something simple ... almost went cross eyed staring at those 2 lines

**Comment by BrianLoveGa** [comment]
cheer controller =   router.post(' /' , (req,res) ......

newCheer.hbs =  <form action='/cheerUps' .... 

__WORKING NOW__
